services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy_server
    restart: always
    ports:
      - "80:80"
      - "2500:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sortlearn_network
    depends_on:
      - frontend

  frontend:
    build: .
    container_name: Sortlearn
    restart: always
    expose:
      - "80"
    networks:
      - sortlearn_network

networks:
  sortlearn_network:
    driver: bridge
